export const ALL_PRODUCTS_REQUEST='ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS='SUCCESS'
export const ALL_PRODUCTS_FAIL='ALL_PRODUCTS_FAIL'
export const CLEAR_ERRORS='CLEAR_ERRORS'

export const SINGLE_PRODUCT_REQUEST ='SINGLE_PRODUCT_REQUEST'
export const SINGLE_PRODUCT_SUCCESS ='SINGLE_PRODUCT_SUCCESS'
export const SINGLE_PRODUCT_FAIL ='SINGLE_PRODUCT_FAIL'